version: '3'

volumes: 
  data:
    driver: local
  
services:

  activemq:
    image: rmohr/activemq:5.15.9-alpine
    ports:
      - "8161:8161"
      - "61616:61616"

  karaf:
    image: pcharoen/karaf:4.0.10
    ports:
      - "8181:8181"
      - "9080:9080"
      - "1099:1099"
      - "8101:8101"
      - "44444:44444"

  graphdb:
    image: pcharoen/graphdb:9.0.0-free
    restart: always
    volumes:
      - data:/opt
      - "./graphdb/import:/opt/graphdb/home/import"
    ports:
      - "7200:7200"
