version: '3'

volumes:
  postgres:
    driver: local
  solr:
    driver: local
  fcrepo:
    driver: local
  redis:
    driver: local
  assets:
    driver: local
  file-storage:
    driver: local
  graphdb:
    driver: local

services:
  postgres:
    restart: always
    image: postgres:9.6-alpine
    env_file: 
      - .env_jupiter

  solr:
    restart: always
    image: solr:6.6
    ports:
      - "8983:8983"
    volumes:
      - solr:/opt/solr/server/solr/mycores
      - ./solr/config:/config
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - jupiter-uat
      - /config

  fcrepo:
    restart: always
    image: pcharoen/fcrepo:4.7.4.t1
    volumes:
      - fcrepo:/fcrepo4-data
    env_file:
      - .env_triplestore
    ports:
      - "8080:8080"
      - "51516:51516"
      - "51513:51513"

  redis:
    restart: always
    image: redis:alpine
    volumes:
      - redis:/data

  # Sidekiq
  worker: &rails
    restart: always
    image: pcharoen/jupiter:1.2.15
    volumes:
      - file-storage:/app/storage/
    command: bundle exec sidekiq
    env_file: .env_jupiter
    depends_on:
      - postgres
      - fcrepo
      - redis
      - solr

  # Rails
  web:
    <<: *rails
    volumes:
      - assets:/app/public/assets/
      - file-storage:/app/storage/
    command: bundle exec puma -e uat

  nginx:
    restart: always
    image: nginx
    depends_on:
      - web
    env_file: .env_jupiter
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - assets:/app/public/assets/
    ports:
      - "80:80"
  
  activemq:
    image: rmohr/activemq:5.15.9-alpine
    ports:
      - "8161:8161"
      - "61616:61616"

  karaf:
    image: pcharoen/karaf:4.0.10
    ports:
      - "8181:8181"
      - "9080:9080"
      - "1099:1099"
      - "8101:8101"
      - "44444:44444"

  graphdb:
    image: pcharoen/graphdb:9.0.0-free
    restart: always
    volumes:
      - graphdb:/opt
#      - "./graphdb/import:/opt/graphdb/home/import"
      - ./graphdb:/opt/graphdb/home
    ports:
      - "7200:7200"
